web/Reports/urls.py
from django.urls import re_path
import django
from . import views
from Reports.models import Report
from web import settings
from django.views.static import serve
from django.conf.urls.static import static


#Не трогайте эту строчку! Добавляйте новые ниже!
urlpatterns = []
urlpatterns += [re_path('static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG})]
urlpatterns += [re_path(r'^reports/$', views.report, name = "reports")]
urlpatterns += [re_path(r'^help/$', views.make_pdf, name = "maker_pdf")] 

web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView
import Users
from Users import urls
from Users.views import VerifiedTokenFunction
from Users.views import SignUpView, ChangePasswordView, profile_edit
from Users.views import user_change
from django.urls import re_path
from django.views.static import serve
from . import settings
from . import views


urlpatterns = []

urlpatterns += [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls, name="admin"),
    path("accounts/", include("django.contrib.auth.urls")),
	path("", include('Reports.urls')),
	path("success",  (TemplateView.as_view(template_name="success.html")), name="success"),
	path('contact-page/', views.contact_page, name = "contact-page"), 
	path('contact-page/send-contact/', views.send_contact, name = "send-contact"), 
	path("", include('Projects.urls')),
	path("", include('Users.urls')),
    path("password_change/", Users.views.ChangePasswordView.as_view(), name='password_change'),
    path("edit/", Users.views.profile_edit, name="edit"),
    path("signup/", VerifiedTokenFunction, name="signup"),
    path("success", Users.views.home, name="home"),
]
urlpatterns += [re_path("signup_reg/(?P<pk>\d+)$", user_change, name="signup_reg"),]
urlpatterns += [path("adminka", RedirectView.as_view(url='/admin', permanent=True), name="adminka"),]

web/Reports/models.py
from django.db import models
from Users.models import User
from Projects.models import Project 
from datetime import datetime, date
import datetime

class Report(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
	report_date = models.DateField(default = date.today)
	message = models.TextField(max_length=1000, help_text="Write any additional comments")
	def get_date(self):
		return "%s - %s" % (self.report_date, self.report_date+datetime.timedelta(weeks=1))
	def __str__(self):
		"""String for representing the Model object."""
		return '%s: %s' % (self.user, self.project)

web/Reports/forms.py
from django import forms
from Projects.models import Project
from Users.models import User

class DateInput(forms.DateInput):
    input_type = 'date'

class FilterForm(forms.Form):
    user = forms.ModelMultipleChoiceField(queryset = User.objects.all(), required = False)
    project = forms.ModelMultipleChoiceField(queryset = Project.objects.all(), required = False)
    left_date = forms.DateField(widget = DateInput(), required = False)
    right_date = forms.DateField(widget = DateInput(), required = False)
    

web/Reports/views.py
import os
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.decorators import user_passes_test
from Projects.models import Project
from Users.models import User
from Reports.models import Report
from .forms import FilterForm
from fpdf import FPDF
import tempfile
from tempfile import TemporaryDirectory as td
from threading import Thread
import time
from django.db.models import Q
from web import settings

def available_reports(request):
	if(request.user.is_staff):
		return Report.objects.all()
	return Report.objects.filter(Q(user__exact = request.user.telegram_id) |
							  Q(project__responsible_user__telegram_id__exact = request.user.telegram_id)).order_by('project')

def available_projects(request):
	if request.user.is_staff:
		return Project.objects.all()
	return request.user.project_set.all()

def available_users(request):
	if request.user.is_staff:
		return User.objects.all()
	users = User.objects.none()
	for project in available_projects(request):
			if(request.user.telegram_id == project.responsible_user.telegram_id):
				users = users | project.users.all()
	return users

def make_pdf(request, reports, path):
	os.makedirs(path, exist_ok = True)
	pdf = FPDF()
	pdf.add_page()
	pdf.add_font("Sans", style = "", fname = os.path.join(settings.BASE_DIR, "Reports/static/Fonts/OpenSans/OpenSans-Regular.ttf"), uni=True)
	pdf.add_font("Sans", style = "B", fname = os.path.join(settings.BASE_DIR, "Reports/static/Fonts/OpenSans/OpenSans-Bold.ttf"), uni=True)
	for report in reports:
		pdf.set_font("Sans", style = "B", size = 12)
		pdf.multi_cell(w = 200, h = 8, txt = 'Project name: ' + report.project.name, align = "L", ln = 1)
		pdf.multi_cell(w = 200, h = 8, txt = 'Week: ' + str(report.report_date), align = "L", ln = 1)
		pdf.multi_cell(w = 200, h = 8, txt = 'Last author: ' + report.user.username, align = "L", ln = 1)
		pdf.multi_cell(w = 200, h = 8, txt = 'Message:', align = "L", ln = 1)
		pdf.set_font("Sans", style = "", size = 12)
		pdf.multi_cell(w = 200, h = 8, txt = report.message, align = "L", ln = 1)
		pdf.multi_cell(w = 200, h = 10, txt = '\n', align = "L", ln = 1)
	pdf.output(path + r"/" + str(request.user) + ".pdf", "F")

@user_passes_test(User.is_verified)
def report(request):
	reports = available_reports(request)
	error_message = ''

	form = FilterForm()
	if request.method == 'POST':
		form = FilterForm(request.POST)
		if(form.is_valid()):
			data = form.cleaned_data
			if(data['project']):
				reports = reports.filter(project__id__in = data['project'])
			if(data['user']):
				reports = reports.filter(user__telegram_id__in = data['user'])
			if(data['left_date']):
				reports = reports.exclude(report_date__lte = data['left_date'])
			if(data['right_date']):
				reports = reports.filter(report_date__lte = data['right_date'])
		else:
			error_message = 'incorrect input data'
			reports = []

	path = r"Reports/static/pdf_folder"
	make_pdf(request, reports, path)

	projects = available_projects(request)
	users = available_users(request)
	if len(users) == 1:
		users.clear()
	if len(projects) == 1:
		projects.clear()
	print(form)
	return render(
		request,
		'Reports/reports_list.html',
		context = {'reports': reports,
			 'projects': projects,
			 'available_users': users,
			 'error_message': error_message,
			 'form': form,
			 'pdfname': r"pdf_folder/" + str(request.user) + ".pdf"})	

web/TeleBot/templates/Reports/reports_list.html
{% extends "base_generic.html" %}
{% load static %}
<script type="text/javascript" src="{% static 'js/sortTable.js' %}"></script>
{% block content %}

<style>

    .table tbody tr:hover td {
        background: #acb7e3; /* Цвет фона при наведении */
        color: #000;
    }

    .table thead tr th:first-child, .table tbody tr td:first-child {
        border-left: 0px solid #21145e;
    }

    .table thead tr th:last-child, .table tbody tr td:last-child {
        border-right: 0px solid #21145e;
    }

    .table tbody tr:nth-child(even) {
        background: #f2f5fc;
    }

    th.sorted[data-order="-1"]::after {
        content: "▼"
    }

    th.sorted[data-order="1"]::after {
        content: "▲"
    }

    .table_a {
        border: 0; /* Граница вокруг таблицы */
        width: 100%;
    }

        .table_a:td {
            border: 0; /* Граница вокруг ячеек */
            empty-cells: hide; /* Прячем пустые ячейки */
            padding: 5px; /* Поля в ячейках */
        }
</style>
<h2 align="center">Отчеты</h2>
<form method="post">
    {% csrf_token %}
    {% if available_users%}
    <table class="table_a">
        <tr>
            <th><label>Дата начала: </label></th>
            <td>{{form.left_date}}<br /></td>
            <th><label>Дата конца: </label></th>
            <td>{{form.right_date}}<br /></td>

        </tr>

        {%endif%}
        {% if projects%}
        <tr>

            <th><label for="id_project">Проект:</label></th>
            <td>{{form.project}}</td>
            <th><label for="id_user">Пользователь:</label></th>
            <td>{{form.user}}</td>
        </tr>
        <br />
        {% endif%}

    </table>

    <br>
    <p align=center>
        <button type="submit" class="btn btn-primary">Фильтрация</button>
        <input type="button" class="btn btn-secondary" id="btnReset" value="Reset" />
    </p>

</form>

{% if error_message%}
<span>{{error_message}}</span>
{% else%}

        {% if reports%}
<p align=left><a href="{% static pdfname %}" class="btn btn-secondary">Загрузить pdf</a></p>

        {% endif%}

            {% if reports%}

<table align=center width=85% id="myTable" class="table">
    <thead class="table-dark">
        <tr>
            <th width=15% onclick="sortTable(0)" align=left>Название проекта</th>
            <th width=10% onclick="sortTable(1)" align=left>Дата</th>
            <th width=15% onclick="sortTable(2)">Пользователь</th>
            <th width=30% onclick="sortTable(3)">Отчет</th>
        </tr>
    </thead>
    <tbody>
        {% for report in reports %}
        <tr>
            <td>{{report.project}}</td>
            <td>{{report.report_date|date:'d-m-Y'}}</td>
            <td>{{report.user}}</td>
            <td>{{report.message}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
            {% else%}
            Нет отчетов.
            {% endif%}
<!---->
<link rel="stylesheet" href="https://davidstutz.github.io/bootstrap-multiselect/docs/css/bootstrap-4.5.2.min.css" type="text/css">
<link rel="stylesheet" href="https://davidstutz.github.io/bootstrap-multiselect/docs/css/bootstrap-example.min.css" type="text/css">
<link rel="stylesheet" href="https://davidstutz.github.io/bootstrap-multiselect/docs/css/prettify.min.css" type="text/css">
<link rel="stylesheet" href="https://davidstutz.github.io/bootstrap-multiselect/docs/css/fontawesome-5.15.1-web/all.css" type="text/css">
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script type="text/javascript" src="https://davidstutz.github.io/bootstrap-multiselect/docs/js/bootstrap.bundle-4.5.2.min.js"></script>
<script type="text/javascript" src="https://davidstutz.github.io/bootstrap-multiselect/docs/js/prettify.min.js"></script>

<link rel="stylesheet" href="https://davidstutz.github.io/bootstrap-multiselect/dist/css/bootstrap-multiselect.css" type="text/css">
<script src="https://davidstutz.github.io/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


<script>

    $('#id_user').multiselect({
        //enableResetButton: true,
        enableFiltering: true,
        maxHeight: 150,
        buttonWidth: 150,
        nonSelectedText: 'Выберите...   ',
        allSelectedText: 'Все ',
        nSelectedText: 'Выбрано',
        includeFilterClearBtn: true,
        includeSelectAllOption: true,
        enableCaseInsensitiveFiltering: true

    });

    $('.multiselect-search').on("keyup", function (e) {
        var keyword = e.target.value;
        if (keyword.length > 2) {
            $.ajax({
                type: "get",
                dataType: "json",
                success: function (response) {
                    $('#id_user').empty() //clear previous options
                    $.each(response, function (i, option) {
                        $('#id_user').append("<option value=" + option.name + ">" + option.name + "</option>") //append to select itself
                    })
                    $('#id_user').multiselect('rebuild') //rebuild your select
                    $('.multiselect-search').val(keyword) //again set search-box..value..it was lost when rebuild
                    $('.multiselect-search').focus()
                }
            });
        }
    });
</script>
<script>

    $('#id_project').multiselect({
        //enableResetButton: true,
        maxHeight: 150,
        buttonWidth: 150,
        nonSelectedText: 'Выберите...   ',
        allSelectedText: 'Все ',
        nSelectedText: 'Выбрано',
        enableFiltering: true,
        includeFilterClearBtn: true,
        includeSelectAllOption: true,
        enableCaseInsensitiveFiltering: true

    });

    $('.multiselect-search').on("keyup", function (e) {
        var keyword = e.target.value;
        if (keyword.length > 2) {
            $.ajax({
                type: "get",
                dataType: "json",
                success: function (response) {
                    $('#id_project').empty() //clear previous options
                    $.each(response, function (i, option) {
                        $('#id_project').append("<option value=" + option.name + ">" + option.name + "</option>") //append to select itself
                    })
                    $('#id_project').multiselect('rebuild') //rebuild your select
                    $('.multiselect-search').val(keyword) //again set search-box..value..it was lost when rebuild
                    $('.multiselect-search').focus()
                }
            });
        }
    });
</script>
<script>
    $("#btnReset").bind("click", function () {
        $('#id_project').multiselect('deselectAll', false);
        $('#id_project').multiselect('updateButtonText');
        $('#id_user').multiselect('deselectAll', false);
        $('#id_user').multiselect('updateButtonText');
        $("input[type=date]").val("");
        $("input[type=date]").selectpicker("refresh");
    });
</script>

{% endif%}
{% endblock %}