web/Users/urls.py
from django.urls import path
from django.urls import re_path
from Users import views
from django.contrib.auth.decorators import user_passes_test


urlpatterns = [
	re_path(r'users/', views.user_list, name='users'),
	re_path(r'^users/archive$', views.ArchivedUsersListView.as_view(), name='archive'),
	re_path(r'^user/(?P<pk>\d+)$',  views.UserDetailView.as_view(), name='user-detail'),
	re_path(r'^user/(?P<pk>\d+)/archive-user$', views.archive_user, name='archive-user'),
	re_path(r'^user/(?P<pk>\d+)/role-user-change$', views.user_role_change, name='role-user-change'),
	]


web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView
import Users
from Users import urls
from Users.views import VerifiedTokenFunction
from Users.views import SignUpView, ChangePasswordView, profile_edit
from Users.views import user_change
from django.urls import re_path
from django.views.static import serve
from . import settings
from . import views


urlpatterns = []

urlpatterns += [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls, name="admin"),
    path("accounts/", include("django.contrib.auth.urls")),
	path("", include('Reports.urls')),
	path("success",  (TemplateView.as_view(template_name="success.html")), name="success"),
	path('contact-page/', views.contact_page, name = "contact-page"), 
	path('contact-page/send-contact/', views.send_contact, name = "send-contact"), 
	path("", include('Projects.urls')),
	path("", include('Users.urls')),
    path("password_change/", Users.views.ChangePasswordView.as_view(), name='password_change'),
    path("edit/", Users.views.profile_edit, name="edit"),
    path("signup/", VerifiedTokenFunction, name="signup"),
    path("success", Users.views.home, name="home"),
]
urlpatterns += [re_path("signup_reg/(?P<pk>\d+)$", user_change, name="signup_reg"),]
urlpatterns += [path("adminka", RedirectView.as_view(url='/admin', permanent=True), name="adminka"),]

web/Projects/models.py
from django.db import models
from Users.models import User
from datetime import datetime, date
from django.urls import reverse    
# Create your models here.
class Project(models.Model):
	name = models.TextField(unique = True, max_length=200)
	start_date = models.DateField(default = datetime.now, null=True, blank=True)
	end_date = models.DateField(null=True, blank=True)
	users = models.ManyToManyField(User)
	responsible_user = models.ForeignKey(User, related_name="responsible", on_delete=models.SET_NULL, null=True)
    
	def __str__(self):
		"""String for representing the Model object."""
		return self.name

	def get_absolute_url(self):
		"""Returns the url to access a particular book instance."""
		return reverse('project-detail', args=[str(self.id)])
	def get_change_url(self):
		return reverse('project-change', args=[str(self.id)])

	def status(self):
		if not self.start_date or date.today()< self.start_date:
			return 'Не начался'
		if self.end_date is None or self.start_date <= date.today() < self.end_date:
			return 'В процессе'
		if date.today() >= self.end_date:
			return 'Завершился'

web/Reports/models.py
from django.db import models
from Users.models import User
from Projects.models import Project 
from datetime import datetime, date
import datetime

class Report(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True)
	report_date = models.DateField(default = date.today)
	message = models.TextField(max_length=1000, help_text="Write any additional comments")
	def get_date(self):
		return "%s - %s" % (self.report_date, self.report_date+datetime.timedelta(weeks=1))
	def __str__(self):
		"""String for representing the Model object."""
		return '%s: %s' % (self.user, self.project)

web/Users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
# Create your models here.

from django.db import models
from django.urls import reverse 
from datetime import date
from django.urls import reverse
	

class User(AbstractUser):
	ROLES = (
		('Unverified', 'Unverified'),
		('Verified', 'Verified'),
		('Administrator', 'Administrator'),
		('Archived', 'Archived'),
   )
	personal_token = models.UUIDField(default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
	telegram_id = models.BigIntegerField(primary_key=True, unique=True)
	role = models.CharField(max_length=50, choices = ROLES, null='Unverified')
	def __str__(self):
		"""String for representing the Model object"""
		return self.username
	def get_absolute_url(self):
		return reverse('user-detail', args=[str(self.telegram_id)])
    
	def my_view(self, request):
		username = None
		if request.user.is_authenticated():
			username = request.user.username

	@property
	def get_role(self):
		if self.role == "Unverified":
			return "Неподтвержденный"
		if self.role == "Verified":
			return "Подтвержденный"
		if self.role == "Administrator":
			return "Администратор"
		if self.role == "Archived":
			return "Архивированный"
		
	
	def is_verified(self):
		return (self.is_active) or (self.is_staff)
class Post(models.Model):
      role_choices = (('Verified', 'Verified'), ('Unverified', 'Unverified'), ('Administrator', 'Administrator'),)	
      role = models.CharField(max_length=50, choices = role_choices)

web/Users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
from .models import Post
from django.forms import ModelForm
from django.contrib.admindocs.utils import ROLES


class UserCreationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name")
    ''' 
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise.forms.ValidationError()
        '''

class VerifiedToken(forms.Form):
    personal_token = forms.UUIDField( help_text="Unique ID for this particular book across whole library")
    #telegram_id = forms.IntegerField()

class UserModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('role',)
        #widgets = {'role' : forms.MultipleChoiceField(choices=Post.role_choices)}
    #class Meta:
        #model = Post
        #role = forms.ChoiceField(choices=choices, widget=forms.RadioSelect())
        #fields = tuple(["role",])
            #choices = (('Verified', 'Verified'), ('Unverified', 'Unverified'), ('Administrator', 'Administrator'),)
            #role = forms.ModelChoiceField(queryset = choices.all(), widget=forms.RadioSelect())
        #widgets = {'role': forms.RadioSelect(attrs={'name': 'role'}, choices=choices)}
       
class UpdateUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = tuple(["username", "first_name", "last_name"])

class UserCreationFormreg(UserCreationForm):
    class Meta:
        model = User
        fields = ("telegram_id",)

web/Users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UpdateUserForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from .forms import UserCreationForm
from .forms import UserCreationFormreg
from .forms import VerifiedToken
from .models import User
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.urls import reverse
from web.settings import REF_TO_BOT
from django.http import Http404
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import user_passes_test
from Users.models import User
from django.contrib.auth.mixins import AccessMixin
from Users.forms import UserModelForm
from django.contrib.admin.views.decorators import staff_member_required


class StaffMixin(AccessMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)
	
class OwnerOrStaffMixin(AccessMixin):
    def handle_no_permission(self):
        return super().handle_no_permission()
    def dispatch(self, request, pk, *args, **kwargs):
        user_page = self.get_object()
        if request.user.telegram_id != user_page.telegram_id and not request.user.is_staff:
            return self.handle_no_permission()
        return super().dispatch(request, pk, *args, **kwargs)
	
#TODO миксины верхний удалить админскую часть



class SignUpView(CreateView):
    form_class = UserCreationFormreg
    success_url = reverse_lazy("login")
    #template_name = "registration/signup.html"
    template_name = "registration/signup.html"

def VerifiedTokenFunction(request):
	error_message = ''
	token = None
	if request.method == 'POST':
		token = request.POST['personal_token']
		try:
			user = User.objects.get(personal_token=token)
			if user.first_name:
				error_message = "Вы уже зарегистрированы в системе!"
			else:
				return HttpResponseRedirect(reverse('signup_reg', args=[user.pk]))
		except ValidationError:
			error_message = "Введённое вами <i>нечто</i> токеном не является!"
		except User.DoesNotExist:
			error_message = "Пользователя с таким токеном не существует"
	return render(request, 'registration/signup_reg.html', context = {"form": VerifiedToken(), "ermsg": error_message, "REF_TO_BOT": REF_TO_BOT})    
   
def user_change(request, pk):
    try:
        user=User.objects.get(pk=pk)
    except User.DoesNotExist:
        error_message = "user deleted"
    if (request.method =='POST'):
        form = UserCreationForm(request.POST, instance=user)
        # Проверка валидности данных формы:
        if form.is_valid():
            user.username = form.cleaned_data['username']
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return HttpResponseRedirect(reverse('login'))
    # Если это GET (или какой-либо ещё), создать форму по умолчанию.
    else:
        form = UserCreationForm(instance=user)
    return render(request, 'registration/signup.html', {'form': form})  
  
class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('success')

@login_required
def home(request):
    tel_id = request.user.telegram_id
    return HttpResponseRedirect(f'Telebot/user/{tel_id}/')

@login_required
def profile_edit(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='success')
    else:
        user_form = UpdateUserForm(instance=request.user)
    return render(request, "edit.html", {'user_form': user_form})


class UsersListView(StaffMixin, generic.ListView):
	model = User
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['user_list'] = User.objects.exclude(role = "Archived")
		return context

	
class ArchivedUsersListView(StaffMixin, generic.ListView):
	model = User
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['user_list'] = User.objects.filter(role = "Archived")
		return context

class UserDetailView(OwnerOrStaffMixin, generic.DetailView):
	model = User

@staff_member_required
def archive_user(request, pk):
	user = User.objects.get(pk = pk)
	if user.is_active:
		user.is_active = False
		user.role = "Archived"
	else:
		user.is_active = True
		if user.is_staff:
			user.role = "Administrator"
		else:
			if user.last_login is None:
				user.role = "Unverified"
			else:	
				user.role = "Verified"
	user.save()
	return redirect(reverse('user-detail', args=[pk]))

@staff_member_required
def user_role_change(request, pk):
    user = User.objects.get(pk = pk)
    if request.method == "POST":
        user.role = request.POST['role']
        if user.role == "Administrator":
            user.is_staff=True
            user.is_active=True
        if user.role == "Verified":
            user.is_staff=False
            user.is_active=True
        if user.role == "Unverified":
            user.is_staff=False
            user.is_active=False
        #form = UserModelForm(request.POST)
        #if(form.is_valid()):
            #user.role = form.cleaned_data['role']
        user.save()
    return HttpResponseRedirect(reverse('user-detail', args=[user.pk]))

#Вывод списка пользователей с возможностью для админов верификации новых пользователей
@staff_member_required
def user_list(request):
	user_list = User.objects.exclude(role = "Archived")
	if request.method == "POST":
		id_list = request.POST.getlist('boxes')
		if request.POST['action'] == "Удалить":
			for user_id in id_list:
				try:
					User.objects.filter(pk=int(user_id)).delete()
				except User.DoesNotExist:
					pass
		else:
			for user_id in id_list:
				try:
					User.objects.filter(pk=int(user_id)).update(is_active=True)
					User.objects.filter(pk=int(user_id)).update(role = "Verified")
				except User.DoesNotExist:
					pass
	return render(request, 'Users/user_list.html', {"user_list" : user_list})



web/templates/Users/user_detail.html
{% extends "base.html" %}
{% block content %}
<meta charset="utf-8">



<style>
.table tbody tr:hover td{
    background: #acb7e3; /* Цвет фона при наведении */
    color:#000;
   }

.table thead tr th:first-child, .table tbody tr td:first-child {
	border-left: 0px solid #21145e;
}
.table thead tr th:last-child, .table tbody tr td:last-child {
	border-right: 0px solid #21145e;
}
.table tbody tr:nth-child(even){
	background: #f2f5fc;
}

</style>

{%if request.user == user%}
<h2 style="text-align:center" class="title">Страница пользователя</h2>
{%endif%}
  <p  align="left"><b>Имя: </b>{{user.first_name }}<br></p>
  <p  align="left"><b>Фамилия: </b>{{user.last_name }}<br></p>
  <p  align="left"><b>Username: </b>{{user.username }}<br></p>
  <p  align="left"><b>Роль: </b>{{user.get_role}} <br></p>
 
    <div class="modal-footer">
	    {%if request.user == user%}
        <a type="button" class="btn btn-primary" href="{%url 'password_change'%}">Изменить пароль</a>
        <a href="{%url 'edit'%}" class="btn btn-primary">Редактировать профиль</a>
      
        {%endif%}
		{%if request.user.is_staff%}
        <a type="button" class="btn btn-primary" href="{%url 'archive-user' user.telegram_id%}">{%if user.role == "Archived"%}Убрать из архива{%else%} Архивировать{%endif%}</a>
        <button class="btn btn-primary my-2 my-sm-0" type="button" data-bs-toggle="modal" data-bs-target="#staticBackdrop1">Изменить роль</button>
        {%endif%}
      </div>

	
	<p  align="center" color="#21145e" ><b>Привязанные проекты:</b><br></p>
    <table class="table">
    <thead class="table-dark">
    <tr>
			<th width = 25% onclick="sortTable(0)"  align=left>Название проекта</th>
			<th width = 20% onclick="sortTable(1)"  align=left>Статус</th>
	</tr> 
    
    </thead>
    <tbody>
    {% for project in user.project_set.all|dictsort:"start_date" %}
    <tr>
		<td><a href="{{ project.get_absolute_url }}" >{{project.name}}</a></td>
        <td >{{project.status}}</td>
    </tr>
        
	{% endfor %}
 </tbody>
    </table>

	    <!---->
               <!-- Модальное окно -->
<form method="POST" action="{% url 'role-user-change' user.telegram_id %}"> 
{%csrf_token%}
<div class="modal fade" id="staticBackdrop1" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Измените роль:</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
     
      <div class="modal-body">
<div class="form-check">
  <input class="form-check-input" type="radio" name="role" value = "Verified" id="id_role1" {%if user.role == "Verified" %} checked {%endif%}>
  <label class="form-check-label" for="id_role1">
    Подтвержденный пользователь
  </label>
</div>
<div class="form-check">
  <input class="form-check-input" type="radio" name="role" value = "Unverified" id="id_role2" {%if user.role == "Unverified" %} checked {%endif%}>
  <label class="form-check-label" for="id_role2">
    Неподтвержденный пользователь
  </label>
</div>
<div class="form-check">
  <input class="form-check-input" type="radio" name="role" value = "Administrator" id="id_role3" {%if user.role == "Administrator"%} checked {%endif%}>
  <label class="form-check-label" for="id_role3">
    Администратор
  </label>
</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </div>
    </div>
  </div>
</div>
</form>
	<!---->
{% endblock %}

web/templates/Users/user_list.html
{% extends "base.html" %}
{% block head %}
{% load static %}
<script type="text/javascript" src="{% static 'js/sortTable.js' %}"></script>
{% endblock %}
{% block content %}

  

	<br>
	<h1 align = center>Список {%if "archive" in request.path%}архивированных{%endif%} пользователей</h1>
	<br>
	{%if "archive" in request.path%}
	<a type="button" class="btn btn-primary" href="{%url 'users'%}">Вернуться к списку пользователей</a>	
	{%else%}
	<a type="button" class="btn btn-primary" href="{%url 'archive'%}">Перейти в архив</a>
	{%endif%}
    {% if user_list %}
	<form method="post">
	{% csrf_token %}
	<p align = center><input class="button" type="submit" name="action" value= "Подтвердить" id = 'cat1' style = 'display: none;'/><input class="button" type="submit" name="action" value= "Удалить" id = 'cat2' style = 'display: none;'/></p>
	<table align = center width = 85%  id="myTable" class="table">
    <thead class="table-dark">
		<tr>
			<th width = 25% onclick="sortTable(0)"  align=left>Nickname</th>
			<th width = 15% onclick="sortTable(1)"  align=left>Имя</th>
			<th width = 20% onclick="sortTable(2)">Фамилия</th>
			<th width = 15% onclick="sortTable(3)">Роль</th>
			<th width = 2% onclick="sortTable(4)">#</th>
			<th width = 10% onclick="sortTable(5)">Число проектов</th>
			<th width = 10% onclick="sortTable(6)">Число отчётов</th>
		</tr> 
    </thead>
    <tbody>
      {% for us in user_list %}
      
      <tr>
        <td><a class="mya" href="{{ us.get_absolute_url }}">{{ us.username }}</a></td>
		<td>				{{us.first_name}}</a></td>
		<td >	{{us.last_name}}</td>
		<td >	{{us.get_role}}</td>
		<td >  
			{% if us.role == "Unverified" %}
  				<input class="form-check-input" type="checkbox" value={{us.telegram_id}} name="boxes" id = 'sb' onchange = 'showOrHide("sb", "cat1", "cat2");'/>
  			{% endif %}
		</td>
		<td >	{{us.project_set.all.count}}</td>
		<td >	{{us.report_set.all.count}}</td>
      </tr>
      {% endfor %}
      </tbody>
	</table>
	<br><br>
	
	</form>
	
	
    {% else %}
      <p>Список пользователей пуст.</p>
    {% endif %} 
    <script type="text/javascript">
  function showOrHide(bloggood, cat_1, cat_2) {
    bloggood = document.getElementById(bloggood);
    cat_1 = document.getElementById(cat_1);
    cat_2 = document.getElementById(cat_2);
    if (bloggood.checked) {cat_1.style.display = "inline-block";cat_2.style.display = "inline-block";}
    else {cat_1.style.display = "none"; cat_2.style.display = "none";}
  }
</script>
 
{% endblock %}